<?php
declare(strict_types=1);
$root=dirname(__DIR__);$core=dirname(__DIR__,2).'/../pam-native/packages/native/src/';$testing=dirname(__DIR__,2).'/pam-native-testing/src/';spl_autoload_register(static function(string$c)use($root,$core,$testing):void{foreach(['Pam\\Native\\Sync\\'=>$root.'/src/','Pam\\Native\\Testing\\'=>$testing,'Pam\\Native\\'=>$core]as$p=>$r)if(str_starts_with($c,$p)){$f=$r.str_replace('\\','/',substr($c,strlen($p))).'.php';if(is_file($f))require$f;return;}});
use Pam\Native\Sync\ConflictPolicy;use Pam\Native\Sync\Contracts\SyncTransport;use Pam\Native\Sync\PolicyConflictResolver;use Pam\Native\Sync\RemoteChange;use Pam\Native\Sync\Storage\InMemorySyncStore;use Pam\Native\Sync\Storage\SQLiteSyncStore;use Pam\Native\Sync\SyncEngine;use Pam\Native\Sync\SyncOperationKind;use Pam\Native\Sync\SyncPullResult;use Pam\Native\Sync\SyncPushResult;use Pam\Native\Sync\SyncRunState;use Pam\Native\Testing\NativeTestHarness;
$tests=[];$test=static function(string$n,Closure$f)use(&$tests):void{$tests[$n]=$f;};
$test('pushes outbox and applies incremental pull',static function():void{$store=new InMemorySyncStore();$transport=new class implements SyncTransport{public array $pushed=[];public function push(array$o,Closure$c):void{$this->pushed=$o;$c(new SyncPushResult(array_map(fn($v)=>$v->identifier,$o)));}public function pull(string$cursor,int$limit,Closure$c):void{$c(new SyncPullResult('cursor-2',[new RemoteChange('todos','one',SyncOperationKind::Upsert,['title'=>'Server'],2,2000)]));}};$engine=new SyncEngine($store,$transport);$engine->upsert('todos','one',['title'=>'Local'],1,static function():void{});$report=null;$engine->synchronize(static function($v)use(&$report):void{$report=$v;});if($report?->state!==SyncRunState::Succeeded||$report->pushed!==1||$report->pulled!==1||$store->record('todos','one')['payload']['title']!=='Server')throw new RuntimeException('sync mismatch');});
$test('client-wins resolver preserves pending local change',static function():void{$store=new InMemorySyncStore();$transport=new class implements SyncTransport{public function push(array$o,Closure$c):void{$c(new SyncPushResult([],['pending'=>'conflict'],1));}public function pull(string$cursor,int$limit,Closure$c):void{$c(new SyncPullResult('c',[new RemoteChange('notes','n1',SyncOperationKind::Upsert,['body'=>'remote'],2,9000)]));}};$engine=new SyncEngine($store,$transport,new PolicyConflictResolver(ConflictPolicy::ClientWins));$engine->upsert('notes','n1',['body'=>'local'],1,static function():void{});$report=null;$engine->synchronize(static function($v)use(&$report):void{$report=$v;});if($store->record('notes','n1')!==null||$report?->conflicts<1)throw new RuntimeException('client conflict lost');});
$test('operation enums are sequential',static function():void{$values=array_map(static fn($v)=>$v->value,SyncOperationKind::cases());if($values!==[1,2])throw new RuntimeException('enum mismatch');});
$test('SQLite adapter uses native prepared operations',static function():void{$fake=NativeTestHarness::install();$fake->succeed('sqlite','transaction');$fake->succeed('sqlite','execute');$fake->succeed('sqlite','query',['rows'=>json_encode([['id'=>'op1','collection_name'=>'todos','record_id'=>'one','operation_kind'=>1,'payload_json'=>'{"title":"A"}','base_version'=>0,'client_timestamp'=>100,'attempts'=>0]],JSON_THROW_ON_ERROR)]);$store=new SQLiteSyncStore();$store->initialize(static function():void{});$operation=new Pam\Native\Sync\SyncOperation('op1','todos','one',SyncOperationKind::Upsert,['title'=>'A'],0,100);$store->enqueue($operation,static function():void{});$pending=[];$store->pending(10,static function($value)use(&$pending):void{$pending=$value;});if(count($pending)!==1||$pending[0]->payload['title']!=='A')throw new RuntimeException('SQLite mapping failed');$fake->assertSatisfied();NativeTestHarness::uninstall();});
$failed=0;foreach($tests as$n=>$f){try{$f();fwrite(STDOUT,"PASS $n\n");}catch(Throwable$e){$failed++;fwrite(STDERR,"FAIL $n: {$e->getMessage()}\n");}}fwrite(STDOUT,count($tests)." tests, $failed failures\n");exit($failed?1:0);
